name: Build
on:
  push:
    branches:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build Project with Dagger
      uses: dagger/dagger-for-github@v5.6.0
      with:
        version: "latest"
        verb: call
        args: build
        cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}