name: Dota2 Helper Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build .NET Example
      uses: dagger/dagger-for-github@v5.6.0
      with:
        version: "latest"
        verb: call
        args: release --directory=./src --tag=env:TAG --token=env:GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ github.ref_name }}