name: Dota2 Helper Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  packages: write  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Release
      uses: dagger/dagger-for-github@v5.6.0
      with:
        version: "latest"
        verb: call
        args: release --git=. --tag=${{ github.ref_name }} --token=env:GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}