name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  packages: write  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Release
      uses: dagger/dagger-for-github@v6.13.0
      with:
        version: "latest"
        verb: call
        args: release --token=env:GITHUB_TOKEN
        cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}